### PR TITLE
Rename twolip to tulip

### PR DESCRIPTION
**Pull request by Fr0st8y7e**

### CODE REVIEW

**Comment by D3nesyan** [comment]
unnecessary

**Comment by justks** [comment]
It's a duplicate device codename in LineageOS so was renamed there to avoid conflict which is not the case on ArrowOS platform.
Hence can stay as it is too to not confuse users or with next release if needed

**Comment by D3nesyan** [comment]
@kubersharma001 ok

**Comment by D3nesyan** [comment]
Please format your commit message to "sdm660-common: ..." and make pr again.

**Comment by D3nesyan** [comment]
and you have to change vendor tree as well.

**Pull request closed without merging**
